"""Add and update team table columns

Revision ID: 37b7c2b87b9f
Revises: e00fddc708c5
Create Date: 2026-07-06 08:26:34.536407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b7c2b87b9f'
down_revision = 'e00fddc708c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('specialties_member_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'team', ['member_id'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_of_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about', sa.String(length=350), nullable=True))
        batch_op.drop_column('experience')
        batch_op.drop_column('info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('about')
        batch_op.drop_column('bio')
        batch_op.drop_column('years_of_experience')

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specialties_member_id_fkey'), 'specialties', ['member_id'], ['id'])

    # ### end Alembic commands ###
