"""Add logo column to socials table

Revision ID: 69f741861191
Revises: 12bad932b4fb
Create Date: 2026-07-04 20:00:04.440668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f741861191'
down_revision = '12bad932b4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socials', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
