"""Add gallery table and update appointments table column name

Revision ID: afa6a64cdbec
Revises: 00c1c97db2ab
Create Date: 2026-07-07 09:18:54.374174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa6a64cdbec'
down_revision = '00c1c97db2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))
        batch_op.drop_column('time_note')

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_note', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('note')

    op.drop_table('categories')
    # ### end Alembic commands ###
