"""Add unique constrait to appointments model

Revision ID: b3a011497bc5
Revises: bcf12f1f0503
Create Date: 2026-07-18 09:55:18.425312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a011497bc5'
down_revision = 'bcf12f1f0503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_booked_slot', ['date', 'time_id', 'stylist_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('uq_booked_slot', type_='unique')

    # ### end Alembic commands ###
