"""add guest info fields

Revision ID: bcf12f1f0503
Revises: c80c2af20d6e
Create Date: 2026-07-15 11:20:35.843984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf12f1f0503'
down_revision = 'c80c2af20d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quest_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('quest_name')

    # ### end Alembic commands ###
