"""Change booking time to Time type, add WeekdaysModel and TeamWorkdaysModel association

Revision ID: cd2fc1baa047
Revises: afa6a64cdbec
Create Date: 2026-07-11 09:18:55.615225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2fc1baa047'
down_revision = 'afa6a64cdbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_num', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_workdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['weekdays.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('ALTER TABLE "time" ALTER COLUMN time TYPE TIME WITHOUT TIME ZONE USING time::time without time zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "time" ALTER COLUMN time TYPE VARCHAR(120) USING time::varchar')

    op.drop_table('team_workdays')
    op.drop_table('weekdays')
    # ### end Alembic commands ###
