"""Update services model foreign keys and relationships

Revision ID: d7f4dc676a80
Revises: 8e2c0e26fa02
Create Date: 2026-07-04 14:25:14.410771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f4dc676a80'
down_revision = '8e2c0e26fa02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_includes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('services_service_includes_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('services_sub_service_id_fkey'), type_='foreignkey')
        batch_op.drop_column('sub_service_id')
        batch_op.drop_column('service_includes_id')

    with op.batch_alter_table('sub_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_includes_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sub_service_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('services_sub_service_id_fkey'), 'sub_services', ['sub_service_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('services_service_includes_id_fkey'), 'service_includes', ['service_includes_id'], ['id'])

    with op.batch_alter_table('service_includes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
