"""Update team and specialties table foreign keys and relationships

Revision ID: e00fddc708c5
Revises: 69f741861191
Create Date: 2026-07-06 08:09:29.094266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00fddc708c5'
down_revision = '69f741861191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'specialties', ['member_id'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('team_specialty_id_fkey'), type_='foreignkey')
        batch_op.drop_column('specialty_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('team_specialty_id_fkey'), 'specialties', ['specialty_id'], ['id'])

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
